//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP4915M
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Item_id { get; set; }
        public Nullable<int> Item_price { get; set; }
        public string Item_Dimension { get; set; }
        public string Item_Weight { get; set; }
    }
}
