//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP4915M
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string item_id { get; set; }
        public int item_price { get; set; }
        public string item_Dimension { get; set; }
        public string item_Weight { get; set; }
        public string item_describe { get; set; }
        public int item_discount { get; set; }
        public string item_name { get; set; }
    }
}
