//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP4915M
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public string item_id { get; set; }
        public string order_id { get; set; }
        public Nullable<int> item_qty { get; set; }
        public Nullable<int> item_weight { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
    }
}
