//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP4915M
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public string order_id { get; set; }
        public string staff_id { get; set; }
        public Nullable<int> order_amount { get; set; }
        public Nullable<System.DateTime> order_created_date { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
